# Generated by Django 4.2.3 on 2024-03-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0003_party_contact_party_gst_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitModel',
        ),
    ]
