# Generated by Django 4.2.3 on 2024-03-15 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0006_remove_party_end_date_remove_party_additionalfield1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedebit',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.parties'),
        ),
    ]
