# Generated by Django 4.2.3 on 2024-03-20 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0007_alter_purchasedebit_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedebit',
            name='dbill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSoftwareapp.purchasebill'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 20)),
        ),
    ]
