# Generated by Django 4.2.3 on 2024-03-22 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0008_purchasedebit_dbill_alter_history_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedebit',
            name='dbill',
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 22)),
        ),
    ]
